# Generated by Django 5.1.2 on 2024-11-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('COURSE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_photos/'),
        ),
    ]
